name: Flutter Build Windows

on:
  push:
    branches: [ main ] # Ganti 'main' jika nama branch utamamu berbeda

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      # 1. Mengambil kode dari repo ke server GitHub
      - uses: actions/checkout@v4

      # 2. Menginstal Flutter SDK di server
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3. Mengambil package/library yang digunakan proyekmu
      - name: Install dependencies
        run: flutter pub get

      # 4. Mengaktifkan fitur desktop windows
      - name: Enable windows support
        run: flutter config --enable-windows-desktop

      # 5. Proses kompilasi menjadi .exe
      - name: Build Windows
        run: flutter build windows --release

      # 6. Menyimpan hasil build agar bisa diunduh
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-app
          # Jalur folder hasil build flutter
          path: build/windows/x64/runner/Release/
